-- MySQL Script generated by MySQL Workbench
-- Sun Jan  6 16:20:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema store_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_system` DEFAULT CHARACTER SET utf8 ;
USE `store_system` ;

-- -----------------------------------------------------
-- Table `store_system`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_system`.`supplier` (
  `supplier_no` VARCHAR(30) NOT NULL,
  `supplier_name` VARCHAR(100) NULL,
  `supplier_addr` VARCHAR(100) NULL,
  `supplier_phone` VARCHAR(20) NULL,
  `supplier_email` VARCHAR(45) NULL,
  PRIMARY KEY (`supplier_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_system`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_system`.`product` (
  `product_no` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `product_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `product_price_vip` DECIMAL(10,2) NOT NULL,
  `product_serial` VARCHAR(45) NOT NULL,
  `product_discount` DECIMAL(3,2) NULL DEFAULT '1',
  `produc_unit` VARCHAR(5) NOT NULL,
  `product_supplier` VARCHAR(30) NULL,
  PRIMARY KEY (`product_no`),
  CONSTRAINT `fk_supplier_supplier_no`
    FOREIGN KEY (`product_supplier`)
    REFERENCES `store_system`.`supplier` (`supplier_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_supplier_supplier_no_idx` ON `store_system`.`product` (`product_supplier` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `store_system`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_system`.`store` (
  `store_no` VARCHAR(30) NOT NULL,
  `store_name` VARCHAR(100) NULL,
  `store_addr` VARCHAR(100) NULL,
  PRIMARY KEY (`store_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_system`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_system`.`user` (
  `user_name` VARCHAR(30) NOT NULL,
  `user_type` INT NOT NULL DEFAULT 1,
  `user_pwd` VARCHAR(512) NOT NULL,
  `user_phone` VARCHAR(15) NULL,
  `user_addr` VARCHAR(100) NULL,
  `user_sign_date` DATETIME NULL,
  PRIMARY KEY (`user_name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
